@extends('layouts.profileLayout')

@section('myProfile')
こんにちは、シリョタです。<br>
現在は25歳のエンジニアです。<br>
<br>
1人前のWeb系エンジニアを目指して日々邁進中！！<br>
本サイトでは作ってみたものを掲載したり、その過程をBlogに書いたりします。<br>
<br>
なぜWeb系？<br>
作ってすぐ公開したり使ってもらえるってすごくいいと思います。<br>
しかも、特殊な機材もなくPCだけでOK！！<br>
……そりゃやるでしょ。やるしかないでしょ。<br>
<br>
あなたの経歴は？<br>
高校から情報工学科に在籍し、プログラムに初めて触れてからそろそろ10年。<br>
大学も情報系に進み、大学院でユーザの感性を学習するモデルについて研究してました！！<br>
その経験を活かし、現在はエンジニアとして勤務中！！<br>
<br>
あなたのSkillは？<br>
実務経験あり！！<br>
　C言語<br>
　Java（サーブレット、JSP）<br>
<br>
最近楽しく使ってます<br>
　HTML<br>
　CSS<br>
　JavaScript（Vue.JS）<br>
　PHP（Laravel）<br>

@endsection
